# Generated by Django 3.0.6 on 2020-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0001_initial'),
        ('Page', '0002_auto_20200530_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='directory',
            field=models.ManyToManyField(null=True, to='Directory.Directory'),
        ),
    ]
