# Generated by Django 3.0.6 on 2020-07-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Directory', '0002_auto_20200713_1915'),
        ('Profile', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='root_directory',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Directory.Directory'),
        ),
    ]
